name: Build and deploy ASP.Net Core app to Azure Web App - bankliteapi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore BankLiteAPI/BankLiteAPI.sln

      - name: Build
        run: dotnet build BankLiteAPI/BankLiteAPI.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test BankLiteAPI/BankLiteAPI.sln --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish BankLiteAPI/BankLite.API/BankLite.API.csproj -c Release -o ./publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_12C8F4232BB8439D8AAEA9750601BA42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_348D98AFABFC4524819299BDE52F4E4D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F4E5E66C7C7F47C6AD88C2DA8F3923A3 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bankliteapi'
          package: .